### ISSUE TITLE
Set up a new profile

### ISSUE THREAD

**Issue by Tiger1988m** [drmrs/auto_pen#1]
Hi,

can someone help me set up a new profile.
I've build a similar one and it works so far out of the box but I am having a raspberry pi 4
and I also wonder where I can change the depth add new speeds and also change the amount of steps needed for a full round.

I highly appreciate your help!

Thanks & Regards

**Comment by drmrs** [comment]
Hello!

https://github.com/drmrs/auto_pen/blob/master/software/auto_pen/cli/configuration.py

Is where profiles live currently.

If you want to create a new profile you could create a new item using `raspberry_pi_1_1600_step_rev_rt` as a template. Assuming you are setup at 1600 steps for a revolution you might call your profile `raspberry_pi_4_1600_step_rev_rt`

Under the speeds you could set the time to sleep between steps to what you like. I might suggest starting adding speeds 5,6,7,8 on top of 1-4 that already exist dropping `step_sleep': 0.00008` to even lower numbers. You need to test these numbers on your pi 4. Remember to update the human descriptions too.

If you need more help you can reach out on a kinky discord server I hang out on. https://discord.gg/9rwcPe

Best wishes.

**Comment by drmrs** [comment]
Submit a PR and I'll merge it in.

**Comment by Tiger1988m** [comment]
Thank you so much it worked pretty good.
I will make a new profile soon for the Raspberry Pi 4 and also new speeds and send it via PR but it will take probably 2 weeks to do so.
